(()=>{const p=document.getElementById("playDemo"),r=document.getElementById("resetDemo"),b=[...document.querySelectorAll(".bubble[data-step]")],s=[...document.querySelectorAll(".circuit-step")],o=document.getElementById("demoResult"),c=document.getElementById("chatStream");let t=[],running=false;const clear=()=>{t.forEach(clearTimeout);t=[]};function step(n){s.forEach(e=>{let x=+e.dataset.step;e.classList.toggle("active",x===n);e.classList.toggle("done",x<n);e.classList.toggle("recorded",x<n)});b.filter(e=>+e.dataset.step===n).forEach((e,i)=>t.push(setTimeout(()=>{e.classList.add("visible");c.scrollTo({top:c.scrollHeight,behavior:"smooth"})},i*420)))}function reset(){clear();running=false;p.disabled=false;p.textContent="▶ Play demo";b.forEach(e=>e.classList.remove("visible"));s.forEach(e=>e.classList.remove("active","done","recorded"));o.classList.remove("visible");c.scrollTo({top:0,behavior:"auto"})}function run(){if(running)return;reset();running=true;p.disabled=true;p.textContent="Demo in progress…";for(let n=1;n<=6;n++)t.push(setTimeout(()=>step(n),(n-1)*1800));t.push(setTimeout(()=>{s.forEach(e=>{e.classList.remove("active");e.classList.add("done","recorded")});o.classList.add("visible");running=false;p.disabled=false;p.textContent="▶ Watch again"},11000))}p.addEventListener("click",run);r.addEventListener("click",reset)})();
;(()=>{const panel=document.getElementById("albyneAssistant"),launcher=document.getElementById("albyneLauncher"),close=document.getElementById("closeAlbyne"),form=document.getElementById("albyneForm"),input=document.getElementById("albyneInput"),chat=document.getElementById("albyneLiveChat");if(!panel)return;
const flow=[
 {q:"Thanks. What kind of business do you run?"},
 {q:"How do you handle that part of the process today?"},
 {q:"What would you like a Digital Employee to do there? For example: answer questions, qualify leads, take requests, follow up or reduce repetitive work."},
 {q:"Where should a person on your team step in?"},
 {q:"Great — that is the kind of customer journey we map before proposing an implementation."}
];let i=0;
function toggle(show){panel.classList.toggle("open",show);panel.setAttribute("aria-hidden",String(!show));if(show)setTimeout(()=>input.focus(),150)}
function msg(text,who){const d=document.createElement("div");d.className="live-msg "+who;d.textContent=text;chat.appendChild(d);chat.scrollTop=chat.scrollHeight}
launcher&&launcher.addEventListener("click",()=>toggle(true));close.addEventListener("click",()=>toggle(false));
form.addEventListener("submit",e=>{e.preventDefault();const value=input.value.trim();if(!value)return;msg(value,"user");input.value="";if(i<flow.length){const q=flow[i].q;i++;setTimeout(()=>msg(q,"bot"),350)}if(i===flow.length){setTimeout(()=>{const d=document.createElement("div");d.className="live-msg bot";d.innerHTML='Want to see this mapped to your real business? <a href="https://www.linkedin.com/in/albinacb/" target="_blank" rel="noopener" style="color:#5f4fbd;font-weight:800">Request a tailored demo with Alby →</a>';chat.appendChild(d);chat.scrollTop=chat.scrollHeight;input.disabled=true;form.querySelector("button").disabled=true},900)}});})();